SHTUKATURNYE_SMESI_PAGE_PROD_URL = "https://stroyrem-nn.ru/catalog/shtukaturnye-smesi"
SHTUKATURNYE_SMESI_PAGE_STAGE_URL = "https://test2.stroyrem-nn.ru/catalog/shtukaturnye-smesi"

CATALOG_PAGE_BUILDING_MATERIALS_TITLE = "Стройматериалы"
CATALOG_PAGE_MAIN_LINK = "Главная"
CATALOG_PAGE_CATALOG_LINK = "Каталог"
CATALOG_PAGE_MORE_LINK = "Еще"
CATALOG_PAGE_GARDEN_TOOLS_TITLE = "Садовый инструмент и инвентарь"
CATALOG_PAGE_TOOLS_LINK = "Ручной и электроинструмент"
CATALOG_PAGE_SHOVELS_TITLE = "Лопаты"
