name: Stroyrem

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Pass credentials
        run: |
          sudo echo "${{ secrets.STROYREM_CREDENTIALS }}" > data/credentials.py
      - name: docker build
        run: |
          sudo docker build -t stroyrem .
      - name: docker run
        run: |
          sudo docker run -v $PWD/allure_result:/app/allure_result stroyrem \
            pytest -s -v --alluredir=allure_result tests/

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          # ref -- branch (or tag in some case)
          ref: gh-pages
          # local path on a virtual machine
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure_result
          allure_history: allure-history
          keep_reports: 20

      - name: Commit Allure report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.MY_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
